dataset: liquor
granularity: day
tsv_file: /Users/yiru/Project/TSExplain/dataset/liquor/liquor2020a.tsv
feature_hier:
  - features:
    - Bottle Volume (ml)
  - features:
    - Category Name
  - features:
    - Pack
  - features:
    - Vendor Name
time_cols:
  - year
  - month
  - day
val_col: Bottles Sold
try_seg_len_ratio: 0.05
try_total_len_ratio: 3
supp_ratio: 0.001
time_min: 2020 1 1
time_max: 2020 6 31
post_process: 7
explain_time_min: 2020 1 1
explain_time_max: 2020 6 31
metric: MChangeAbs
topK: 3
pred_len: 3
sim: mutual
seg_number: 20
min_len: 2
min_dist: 0
cascading_opt: 1
