dataset: sp500
granularity: day
tsv_file: /Users/yiru/Project/TSExplain/dataset/sp500/sp500.tsv
feature_hier:
  - features:
    - category
    - subcategory
    - symbol
time_cols:
  - month
  - day
val_col: freeCap853
try_seg_len_ratio: 0.05
try_total_len_ratio: 3
supp_ratio: 0.001
time_min: 1 1
time_max: 12 31
post_process: 7
explain_time_min: 1 1
explain_time_max: 12 31
metric: MChangeAbs
topK: 3
pred_len: 3
sim: mutual
seg_number: 20
min_len: 2
min_dist: 0
cascading_opt: 1
